### ISSUE TITLE
Video not showing when build with sdk 33 in Android 13

### ISSUE THREAD

**Issue by newbieGit123** [react-native-cameraroll/react-native-cameraroll#490]
### Summary
Not able to fetch Videos when build in RN version 0.71.0 with sdk 33, in Android 13.

`
CameraRoll.getPhotos({assetType: "Videos"});
`

**Comment by HERYORDEJY-DEV** [comment]
@newbieGit123  - on your end does it show Videos for iOS, and have you been able to solve the Android issue?

**Comment by jainminals** [comment]
CameraRoll.getPhotos({
      assetType: "Photos",
      first: 10,
    })

 "react-native": "0.71.6",

for ios working fine, not in android ....

**Comment by joshnissenbaum** [comment]
Same issue - no videos on Android 13. Anyone know of any other libraries actively maintained for this?

**Comment by joshnissenbaum** [comment]
For anyone wondering, this was solved on Android 13 by requesting the `READ_MEDIA_VIDEO` permission.


```
  const requestPermissionsAndroid = useCallback(async () => {
    const permission = Platform.Version >= 33 ? PermissionsAndroid.PERMISSIONS.READ_MEDIA_VIDEO : PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE;

    const hasPermission = await PermissionsAndroid.check(permission);
    if (hasPermission) {
      return true;
    }

    const status = await PermissionsAndroid.request(permission);
    return status === 'granted';
  }, []);
```

**Comment by jainminals** [comment]
Thanks sir , let me check if it's working.😇😇

**Comment by Arjan-Zuidema** [comment]
Looks like we need to update the docs to request additional permission for video's on Android. I will create an issue for it.

Probably you want to request both `READ_MEDIA_VIDEO` and `READ_MEDIA_IMAGES`

Thanks @joshnissenbaum for researching this.

**Comment by abdulllahshahid** [comment]
Still Not working. How it will closed. Please guide me how to use it in Android 13.

**Comment by jainminals** [comment]
It's working fine.. thanks

**Comment by Arjan-Zuidema** [comment]
> Still Not working. How it will closed. Please guide me how to use it in Android 13.
> 
> I am facing in Images and videos both
> 
> 

Have you checked the docs about the Android 13 permissies? It should work fine

**Comment by chienvuvan99** [comment]
I'm also facing a similar issue. It works fine on Android below version 13. I suspect the problem lies with the URI that the library returns.
